# Generated by Django 3.2.12 on 2022-03-25 21:10

from django.db import migrations


def assign_slug(apps, schema_editor):
    Posts = apps.get_model('Posts', 'Posts')
    posts = Posts.objects.all()
    for post in posts:
        slug = post.slug
        if posts.filter(slug=slug).exclude(pk=post.pk).exists():
            post.slug += str(post.id)
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_set_slug_required'),
    ]

    operations = [
        migrations.RunPython(assign_slug)
    ]
