# Generated by Django 3.2.12 on 2022-03-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
