# Generated by Django 3.2.12 on 2022-03-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='field_type',
            field=models.CharField(choices=[('Phone', 'phone'), ('Link', 'link'), ('Email', 'email')], max_length=10, null=True),
        ),
    ]
