# Generated by Django 3.2.12 on 2022-03-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0002_contacts_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='field_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('link', 'Link'), ('email', 'Email')], max_length=10, null=True),
        ),
    ]
