# Generated by Django 3.2.12 on 2022-04-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0003_fix_field_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
