# Generated by Django 3.2.12 on 2022-04-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20220312_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, null=True, unique=True, verbose_name='email address'),
        ),
    ]
